# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: source_code_parser/protobuf/source_code_parser.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4source_code_parser/protobuf/source_code_parser.proto\"8\n\x12SyntaxParseRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\"&\n\x13SyntaxParseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32P\n\x10SourceCodeParser\x12<\n\x0bSyntaxParse\x12\x13.SyntaxParseRequest\x1a\x14.SyntaxParseResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'source_code_parser.protobuf.source_code_parser_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNTAXPARSEREQUEST']._serialized_start=56
  _globals['_SYNTAXPARSEREQUEST']._serialized_end=112
  _globals['_SYNTAXPARSERESPONSE']._serialized_start=114
  _globals['_SYNTAXPARSERESPONSE']._serialized_end=152
  _globals['_SOURCECODEPARSER']._serialized_start=154
  _globals['_SOURCECODEPARSER']._serialized_end=234
# @@protoc_insertion_point(module_scope)
